sudo: required
dist: trusty
language: ruby

before_install:
before_install:
- gem install asciidoctor -v 1.5.2
- gem install tilt
- sudo pip install git+https://github.com/gitenberg-dev/gitberg
- sudo pip install pillow
- sudo pip install cssutils
- sudo pip install docutils
- sudo pip install roman
- sudo pip install git+https://github.com/gitenberg-dev/pg-epubmaker
script:
- VERSION=`ruby -e "require 'yaml'; meta = YAML.load_file('metadata.yaml'); puts meta['_version'];"`
- git clone https://github.com/gitenberg-dev/asciidoctor-htmlbook.git
- sudo pip install -r asciidoctor-htmlbook/gitberg-machine/requirements.txt

- /usr/bin/python -c "from gitenberg import travis; travis.build_epub()"
- ebook-convert book.epub book.mobi
- xvfb-run ebook-convert book.epub book.pdf
branches:
  only:
  - master
notifications:
  webhooks:
    urls:
      - https://unglue.it/api/travisci/webhook
    on_success: always
    on_failure: never
    on_start: never
deploy:
  skip_cleanup: true
  provider: releases
  api_key:
    secure: gv7ie40zexyEq2vy4CnEbH+ecYlrgqQDDEKQbOkR71lwx4XUYkyn+59yP8YvK+nhXJToqiTqDvOoTdoAxNDSXRIokBtGAu3z+T5+7GUrLKM33lSL86gIfsScTjHsV7YJtl3V4t5+b+Vo9gNMXKbhZ0FYLaQ+ntai9HmWE3FPltaAmd3jAtcCRKaDHKanVqmNp23QgbhXyFOUI4GxRxYFNMcZu7NR2sLAkdIpJ1M+NiiBfbSaRRDAwLgQmuRtWQXUqEEbAJpUHuqU/h12qkhjNTGrsr8j/spNYiQvCgOOd2eQg1Md7lhV3hAYe38rnibr+i9V+hNrGEMcLUYoirwVJe+iQuioRBhAkozbJ6FObFxTMgf5PX7/tFOw4EEBkVVFVxa/NRN16YgFF8nCZThvOGm+evt7tpBaBPBEI8WZetXIYDh2/kL6KcvcxHMltezuv1qCj6T+XibVsJh4zAuNv0W45yZSJnc5VFlnRmNdBM+2iGaB9pyHMKjFucrV7fe6XhyH3uCx6HvCZ8Op47GwvOA+KqacXIZsOeEBAHzrbN2HmWuzC+uPTPMElUAVgN+t21pyb+3WzHuQpLfzDWoYMols6025l5k5l3B61lOqpKTYZkBXxQM6bhr4BgQQsPfvqm4CVlY9lSkzz5hmCH7DU6uBYWl1kG+zMCvzre1yKQY=
  file:
    - book.epub
    - book.mobi
    - book.pdf
  "on":
    repo: GITenberg/Bab--A-Sub-Deb_366
addons:
  apt:
    packages:
    - xsltproc
    - xvfb
    - calibre
    - python-pip
    - git
    - python-dev
    - libjpeg-dev
    - libpng-dev
    - libfreetype6
    - libfreetype6-dev
    - zlib1g-dev
    - python-lxml
    - libxml2-dev
    - libxslt1-dev
    - tidy